//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:18 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class ArticleChildComment
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 对应的评论ID
		/// </summary>		
		public int CommentId { get; set; }
		
		/// <summary>
		/// 内容
		/// </summary>		
		public string Content { get; set; }
		
		/// <summary>
		/// 来自的用户的Id
		/// </summary>		
		public int FromUserId { get; set; }
		
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 来自用户的名字
		/// </summary>		
		public string FromUserName { get; set; }
		
		/// <summary>
		/// 0：未审核  1:已审核 2:已删除
		/// </summary>		
		public int Status { get; set; }
		   
    }
}

