//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:19 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class Hc_WebMenu
    {
		
		/// <summary>
		/// 主键ID
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EnName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Url { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Img { get; set; }
		
		/// <summary>
		/// 添加时间
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ThemeName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string EnThemeName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Memo { get; set; }
		   
    }
}

