//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:19 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class MemberCourseList
    {
		
		/// <summary>
		/// 主键ID
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 用户Id
		/// </summary>		
		public int MemberId { get; set; }
		
		/// <summary>
		/// 名称
		/// </summary>		
		public string Title { get; set; }
		
		/// <summary>
		/// 课程简介
		/// </summary>		
		public string Memo { get; set; }
		
		/// <summary>
		/// 开始时间
		/// </summary>		
		public string StartTime { get; set; }
		
		/// <summary>
		/// 结束时间
		/// </summary>		
		public string EndTime { get; set; }
		
		/// <summary>
		/// 音频视频
		/// </summary>		
		public string Vedio { get; set; }
		
		/// <summary>
		/// 小标题
		/// </summary>		
		public string MinTitle { get; set; }
		
		/// <summary>
		/// 时长
		/// </summary>		
		public string Time { get; set; }
		
		/// <summary>
		/// 分类
		/// </summary>		
		public int Type { get; set; }
		
		/// <summary>
		/// 价格
		/// </summary>		
		public decimal Price { get; set; }
		
		/// <summary>
		/// 评分
		/// </summary>		
		public int Grade { get; set; }
		
		/// <summary>
		/// 添加时间
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		   
    }
}

