//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:19 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class MemberList
    {
		
		/// <summary>
		/// 主键ID
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 名称
		/// </summary>		
		public string Name { get; set; }
		
		/// <summary>
		/// 地址
		/// </summary>		
		public string Address { get; set; }
		
		/// <summary>
		/// 头像
		/// </summary>		
		public string Img { get; set; }
		
		/// <summary>
		/// 性别
		/// </summary>		
		public int Sex { get; set; }
		
		/// <summary>
		/// 0:普通 1:占星师 2:漫画师
		/// </summary>		
		public int MemberType { get; set; }
		
		/// <summary>
		/// 手机
		/// </summary>		
		public string Mobile { get; set; }
		
		/// <summary>
		/// 密码
		/// </summary>		
		public string Password { get; set; }
		
		/// <summary>
		/// 登录账号
		/// </summary>		
		public string LoginName { get; set; }
		
		/// <summary>
		/// 生日
		/// </summary>		
		public DateTime BirthDay { get; set; }
		
		/// <summary>
		/// 星座
		/// </summary>		
		public int Astro { get; set; }
		
		/// <summary>
		/// 邮箱
		/// </summary>		
		public string Email { get; set; }
		
		/// <summary>
		/// 添加时间
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		   
    }
}

