//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:19 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class MemberImgList
    {
		
		/// <summary>
		/// 主键ID
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 用户Id
		/// </summary>		
		public int MemberId { get; set; }
		
		/// <summary>
		/// 标题
		/// </summary>		
		public string Title { get; set; }
		
		/// <summary>
		/// 0:私有 1:摄影 2:生活
		/// </summary>		
		public int Type { get; set; }
		
		/// <summary>
		/// 评论数
		/// </summary>		
		public int CommentCount { get; set; }
		
		/// <summary>
		/// 点赞数
		/// </summary>		
		public int ZanCount { get; set; }
		
		/// <summary>
		/// 照片
		/// </summary>		
		public string Img { get; set; }
		
		/// <summary>
		/// 是否推荐
		/// </summary>		
		public int IsTop { get; set; }
		
		/// <summary>
		/// 添加时间
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		   
    }
}

