//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:19 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class OTALoginLog
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OTAMSGUID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int UserId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string LoginName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string IP { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Memo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsDel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		   
    }
}

