//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:19 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class OTAUsers
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string OTAMSGUID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string LoginName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string RealName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Email { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PassWord { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsAdmin { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int DepartmentId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int UserType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Mobile { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Address { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsLeader { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int IsDel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Img { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int PostId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Gender { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string DepartName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string PostName { get; set; }
		   
    }
}

