
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-09-10 13:23:42 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Ast.IDal;
using Ast.Models;

namespace Ast.Dal
{	 
	 
	 public partial class ArticleChildCommentDal : BaseDal<ArticleChildComment>, IArticleChildCommentDal { }
	 
	 public partial class ArticleCommentListDal : BaseDal<ArticleCommentList>, IArticleCommentListDal { }
	 
	 public partial class ArticleListDal : BaseDal<ArticleList>, IArticleListDal { }
	 
	 public partial class ArticleMarkListDal : BaseDal<ArticleMarkList>, IArticleMarkListDal { }
	 
	 public partial class ArticleTypeListDal : BaseDal<ArticleTypeList>, IArticleTypeListDal { }
	 
	 public partial class BannerListDal : BaseDal<BannerList>, IBannerListDal { }
	 
	 public partial class ClubChildCommentDal : BaseDal<ClubChildComment>, IClubChildCommentDal { }
	 
	 public partial class ClubPostCommentListDal : BaseDal<ClubPostCommentList>, IClubPostCommentListDal { }
	 
	 public partial class ClubPostListDal : BaseDal<ClubPostList>, IClubPostListDal { }
	 
	 public partial class ClubPostTypeDal : BaseDal<ClubPostType>, IClubPostTypeDal { }
	 
	 public partial class Hc_ArticleListDal : BaseDal<Hc_ArticleList>, IHc_ArticleListDal { }
	 
	 public partial class Hc_BannerListDal : BaseDal<Hc_BannerList>, IHc_BannerListDal { }
	 
	 public partial class Hc_WebMenuDal : BaseDal<Hc_WebMenu>, IHc_WebMenuDal { }
	 
	 public partial class Hc_WebSettingDal : BaseDal<Hc_WebSetting>, IHc_WebSettingDal { }
	 
	 public partial class LinksListDal : BaseDal<LinksList>, ILinksListDal { }
	 
	 public partial class MemberArticleListDal : BaseDal<MemberArticleList>, IMemberArticleListDal { }
	 
	 public partial class MemberCommentListDal : BaseDal<MemberCommentList>, IMemberCommentListDal { }
	 
	 public partial class MemberCourseListDal : BaseDal<MemberCourseList>, IMemberCourseListDal { }
	 
	 public partial class MemberImgListDal : BaseDal<MemberImgList>, IMemberImgListDal { }
	 
	 public partial class MemberListDal : BaseDal<MemberList>, IMemberListDal { }
	 
	 public partial class OTADepartmentDal : BaseDal<OTADepartment>, IOTADepartmentDal { }
	 
	 public partial class OTAFuncMenusDal : BaseDal<OTAFuncMenus>, IOTAFuncMenusDal { }
	 
	 public partial class OTALoginLogDal : BaseDal<OTALoginLog>, IOTALoginLogDal { }
	 
	 public partial class OTAMailListDal : BaseDal<OTAMailList>, IOTAMailListDal { }
	 
	 public partial class OTAMenuDal : BaseDal<OTAMenu>, IOTAMenuDal { }
	 
	 public partial class OTAMsgListDal : BaseDal<OTAMsgList>, IOTAMsgListDal { }
	 
	 public partial class OTAPostDal : BaseDal<OTAPost>, IOTAPostDal { }
	 
	 public partial class OTAUsersDal : BaseDal<OTAUsers>, IOTAUsersDal { }
	 
	 public partial class SchoolListDal : BaseDal<SchoolList>, ISchoolListDal { }
	 
	 public partial class SysNoticeListDal : BaseDal<SysNoticeList>, ISysNoticeListDal { }
	 
	 public partial class SysNoticeTypeDal : BaseDal<SysNoticeType>, ISysNoticeTypeDal { }
	 
	 public partial class UsersDal : BaseDal<Users>, IUsersDal { }
	}
