
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-09-10 13:23:49 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Ast.Dal;
using Ast.IDal;
namespace Ast.DalFactory
{	 
	public partial class DbSession:IDbSession
	{
	 
	 public IArticleChildCommentDal ArticleChildCommentDal
        {
            get { return new ArticleChildCommentDal(); }
        }
	 
	 public IArticleCommentListDal ArticleCommentListDal
        {
            get { return new ArticleCommentListDal(); }
        }
	 
	 public IArticleListDal ArticleListDal
        {
            get { return new ArticleListDal(); }
        }
	 
	 public IArticleMarkListDal ArticleMarkListDal
        {
            get { return new ArticleMarkListDal(); }
        }
	 
	 public IArticleTypeListDal ArticleTypeListDal
        {
            get { return new ArticleTypeListDal(); }
        }
	 
	 public IBannerListDal BannerListDal
        {
            get { return new BannerListDal(); }
        }
	 
	 public IClubChildCommentDal ClubChildCommentDal
        {
            get { return new ClubChildCommentDal(); }
        }
	 
	 public IClubPostCommentListDal ClubPostCommentListDal
        {
            get { return new ClubPostCommentListDal(); }
        }
	 
	 public IClubPostListDal ClubPostListDal
        {
            get { return new ClubPostListDal(); }
        }
	 
	 public IClubPostTypeDal ClubPostTypeDal
        {
            get { return new ClubPostTypeDal(); }
        }
	 
	 public IHc_ArticleListDal Hc_ArticleListDal
        {
            get { return new Hc_ArticleListDal(); }
        }
	 
	 public IHc_BannerListDal Hc_BannerListDal
        {
            get { return new Hc_BannerListDal(); }
        }
	 
	 public IHc_WebMenuDal Hc_WebMenuDal
        {
            get { return new Hc_WebMenuDal(); }
        }
	 
	 public IHc_WebSettingDal Hc_WebSettingDal
        {
            get { return new Hc_WebSettingDal(); }
        }
	 
	 public ILinksListDal LinksListDal
        {
            get { return new LinksListDal(); }
        }
	 
	 public IMemberArticleListDal MemberArticleListDal
        {
            get { return new MemberArticleListDal(); }
        }
	 
	 public IMemberCommentListDal MemberCommentListDal
        {
            get { return new MemberCommentListDal(); }
        }
	 
	 public IMemberCourseListDal MemberCourseListDal
        {
            get { return new MemberCourseListDal(); }
        }
	 
	 public IMemberImgListDal MemberImgListDal
        {
            get { return new MemberImgListDal(); }
        }
	 
	 public IMemberListDal MemberListDal
        {
            get { return new MemberListDal(); }
        }
	 
	 public IOTADepartmentDal OTADepartmentDal
        {
            get { return new OTADepartmentDal(); }
        }
	 
	 public IOTAFuncMenusDal OTAFuncMenusDal
        {
            get { return new OTAFuncMenusDal(); }
        }
	 
	 public IOTALoginLogDal OTALoginLogDal
        {
            get { return new OTALoginLogDal(); }
        }
	 
	 public IOTAMailListDal OTAMailListDal
        {
            get { return new OTAMailListDal(); }
        }
	 
	 public IOTAMenuDal OTAMenuDal
        {
            get { return new OTAMenuDal(); }
        }
	 
	 public IOTAMsgListDal OTAMsgListDal
        {
            get { return new OTAMsgListDal(); }
        }
	 
	 public IOTAPostDal OTAPostDal
        {
            get { return new OTAPostDal(); }
        }
	 
	 public IOTAUsersDal OTAUsersDal
        {
            get { return new OTAUsersDal(); }
        }
	 
	 public ISchoolListDal SchoolListDal
        {
            get { return new SchoolListDal(); }
        }
	 
	 public ISysNoticeListDal SysNoticeListDal
        {
            get { return new SysNoticeListDal(); }
        }
	 
	 public ISysNoticeTypeDal SysNoticeTypeDal
        {
            get { return new SysNoticeTypeDal(); }
        }
	 
	 public IUsersDal UsersDal
        {
            get { return new UsersDal(); }
        }
		}
}
