//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-09-10 13:24:14 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class ArticleCommentList
    {
		
		/// <summary>
		/// 主键ID
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 文章Id
		/// </summary>		
		public int ArticleId { get; set; }
		
		/// <summary>
		/// 评论者id
		/// </summary>		
		public int UserId { get; set; }
		
		/// <summary>
		/// 文章评论
		/// </summary>		
		public string Content { get; set; }
		
		/// <summary>
		/// 点赞数
		/// </summary>		
		public int LikeNum { get; set; }
		
		/// <summary>
		/// 反对数
		/// </summary>		
		public int UnLikeNum { get; set; }
		
		/// <summary>
		/// 0：未审核  1:已审核 2:已删除
		/// </summary>		
		public int Status { get; set; }
		
		/// <summary>
		/// 操作人
		/// </summary>		
		public int CreateUser { get; set; }
		
		/// <summary>
		/// 添加时间
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		   
    }
}

