//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-09-10 13:24:14 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class ArticleTypeList
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ParentId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Memo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Title { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Keywords { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Description { get; set; }
		   
    }
}

