//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-09-10 13:24:15 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class Hc_ArticleList
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Title { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MenuId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string HcContent { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		
		/// <summary>
		/// 文章收藏数
		/// </summary>		
		public int LookNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int MarkId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Editor { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string TopImg { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Brief { get; set; }
		
		/// <summary>
		/// Pc主页显示 0：不主页显示 1：主页显示
		/// </summary>		
		public int Status { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int ReadNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int CommentNum { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int Sort { get; set; }
		   
    }
}

