//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-09-10 13:24:15 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Ast.Models
{	
	public partial class Hc_WebSetting
    {
		
		/// <summary>
		/// 主键ID
		/// </summary>		
		public int Id { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Url { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Memo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Logo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SEOKeywords { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SEOTitle { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string SEODescription { get; set; }
		
		/// <summary>
		/// 添加时间
		/// </summary>		
		public DateTime AddTime { get; set; }
		
		/// <summary>
		/// 修改时间
		/// </summary>		
		public DateTime ModifyTime { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Adderss { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Tel { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Email { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string QQ { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Wechat { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Weibo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Map { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string FullName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string BeiAnNo { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string IndexLogo { get; set; }
		   
    }
}

