
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:00 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Ast.Models;

namespace Ast.IDal
{	 
	 
	 public partial interface IArticleChildCommentDal : IBaseDal<ArticleChildComment>{}
	 
	 public partial interface IArticleCommentListDal : IBaseDal<ArticleCommentList>{}
	 
	 public partial interface IArticleListDal : IBaseDal<ArticleList>{}
	 
	 public partial interface IArticleMarkListDal : IBaseDal<ArticleMarkList>{}
	 
	 public partial interface IArticleTypeListDal : IBaseDal<ArticleTypeList>{}
	 
	 public partial interface IBannerListDal : IBaseDal<BannerList>{}
	 
	 public partial interface IClubChildCommentDal : IBaseDal<ClubChildComment>{}
	 
	 public partial interface IClubPostCommentListDal : IBaseDal<ClubPostCommentList>{}
	 
	 public partial interface IClubPostListDal : IBaseDal<ClubPostList>{}
	 
	 public partial interface IClubPostTypeDal : IBaseDal<ClubPostType>{}
	 
	 public partial interface IHc_ArticleListDal : IBaseDal<Hc_ArticleList>{}
	 
	 public partial interface IHc_BannerListDal : IBaseDal<Hc_BannerList>{}
	 
	 public partial interface IHc_WebMenuDal : IBaseDal<Hc_WebMenu>{}
	 
	 public partial interface IHc_WebSettingDal : IBaseDal<Hc_WebSetting>{}
	 
	 public partial interface ILinksListDal : IBaseDal<LinksList>{}
	 
	 public partial interface IMemberArticleListDal : IBaseDal<MemberArticleList>{}
	 
	 public partial interface IMemberCommentListDal : IBaseDal<MemberCommentList>{}
	 
	 public partial interface IMemberCourseListDal : IBaseDal<MemberCourseList>{}
	 
	 public partial interface IMemberImgListDal : IBaseDal<MemberImgList>{}
	 
	 public partial interface IMemberListDal : IBaseDal<MemberList>{}
	 
	 public partial interface IOTADepartmentDal : IBaseDal<OTADepartment>{}
	 
	 public partial interface IOTAFuncMenusDal : IBaseDal<OTAFuncMenus>{}
	 
	 public partial interface IOTALoginLogDal : IBaseDal<OTALoginLog>{}
	 
	 public partial interface IOTAMailListDal : IBaseDal<OTAMailList>{}
	 
	 public partial interface IOTAMenuDal : IBaseDal<OTAMenu>{}
	 
	 public partial interface IOTAMsgListDal : IBaseDal<OTAMsgList>{}
	 
	 public partial interface IOTAPostDal : IBaseDal<OTAPost>{}
	 
	 public partial interface IOTAUsersDal : IBaseDal<OTAUsers>{}
	 
	 public partial interface ISchoolListDal : IBaseDal<SchoolList>{}
	 
	 public partial interface ISysNoticeListDal : IBaseDal<SysNoticeList>{}
	 
	 public partial interface ISysNoticeTypeDal : IBaseDal<SysNoticeType>{}
	 
	 public partial interface IUsersDal : IBaseDal<Users>{}
	}
