
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:04 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ast.IDal
{	 
	public partial interface IDbSession
	{
	 
	 IArticleChildCommentDal ArticleChildCommentDal { get; }
	 
	 IArticleCommentListDal ArticleCommentListDal { get; }
	 
	 IArticleListDal ArticleListDal { get; }
	 
	 IArticleMarkListDal ArticleMarkListDal { get; }
	 
	 IArticleTypeListDal ArticleTypeListDal { get; }
	 
	 IBannerListDal BannerListDal { get; }
	 
	 IClubChildCommentDal ClubChildCommentDal { get; }
	 
	 IClubPostCommentListDal ClubPostCommentListDal { get; }
	 
	 IClubPostListDal ClubPostListDal { get; }
	 
	 IClubPostTypeDal ClubPostTypeDal { get; }
	 
	 IHc_ArticleListDal Hc_ArticleListDal { get; }
	 
	 IHc_BannerListDal Hc_BannerListDal { get; }
	 
	 IHc_WebMenuDal Hc_WebMenuDal { get; }
	 
	 IHc_WebSettingDal Hc_WebSettingDal { get; }
	 
	 ILinksListDal LinksListDal { get; }
	 
	 IMemberArticleListDal MemberArticleListDal { get; }
	 
	 IMemberCommentListDal MemberCommentListDal { get; }
	 
	 IMemberCourseListDal MemberCourseListDal { get; }
	 
	 IMemberImgListDal MemberImgListDal { get; }
	 
	 IMemberListDal MemberListDal { get; }
	 
	 IOTADepartmentDal OTADepartmentDal { get; }
	 
	 IOTAFuncMenusDal OTAFuncMenusDal { get; }
	 
	 IOTALoginLogDal OTALoginLogDal { get; }
	 
	 IOTAMailListDal OTAMailListDal { get; }
	 
	 IOTAMenuDal OTAMenuDal { get; }
	 
	 IOTAMsgListDal OTAMsgListDal { get; }
	 
	 IOTAPostDal OTAPostDal { get; }
	 
	 IOTAUsersDal OTAUsersDal { get; }
	 
	 ISchoolListDal SchoolListDal { get; }
	 
	 ISysNoticeListDal SysNoticeListDal { get; }
	 
	 ISysNoticeTypeDal SysNoticeTypeDal { get; }
	 
	 IUsersDal UsersDal { get; }
		}
}
