
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:13 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Ast.Models;

namespace Ast.IBll
{	 
	 
	public partial interface IArticleChildCommentService : IBaseService<ArticleChildComment>{}
	 
	public partial interface IArticleCommentListService : IBaseService<ArticleCommentList>{}
	 
	public partial interface IArticleListService : IBaseService<ArticleList>{}
	 
	public partial interface IArticleMarkListService : IBaseService<ArticleMarkList>{}
	 
	public partial interface IArticleTypeListService : IBaseService<ArticleTypeList>{}
	 
	public partial interface IBannerListService : IBaseService<BannerList>{}
	 
	public partial interface IClubChildCommentService : IBaseService<ClubChildComment>{}
	 
	public partial interface IClubPostCommentListService : IBaseService<ClubPostCommentList>{}
	 
	public partial interface IClubPostListService : IBaseService<ClubPostList>{}
	 
	public partial interface IClubPostTypeService : IBaseService<ClubPostType>{}
	 
	public partial interface IHc_ArticleListService : IBaseService<Hc_ArticleList>{}
	 
	public partial interface IHc_BannerListService : IBaseService<Hc_BannerList>{}
	 
	public partial interface IHc_WebMenuService : IBaseService<Hc_WebMenu>{}
	 
	public partial interface IHc_WebSettingService : IBaseService<Hc_WebSetting>{}
	 
	public partial interface ILinksListService : IBaseService<LinksList>{}
	 
	public partial interface IMemberArticleListService : IBaseService<MemberArticleList>{}
	 
	public partial interface IMemberCommentListService : IBaseService<MemberCommentList>{}
	 
	public partial interface IMemberCourseListService : IBaseService<MemberCourseList>{}
	 
	public partial interface IMemberImgListService : IBaseService<MemberImgList>{}
	 
	public partial interface IMemberListService : IBaseService<MemberList>{}
	 
	public partial interface IOTADepartmentService : IBaseService<OTADepartment>{}
	 
	public partial interface IOTAFuncMenusService : IBaseService<OTAFuncMenus>{}
	 
	public partial interface IOTALoginLogService : IBaseService<OTALoginLog>{}
	 
	public partial interface IOTAMailListService : IBaseService<OTAMailList>{}
	 
	public partial interface IOTAMenuService : IBaseService<OTAMenu>{}
	 
	public partial interface IOTAMsgListService : IBaseService<OTAMsgList>{}
	 
	public partial interface IOTAPostService : IBaseService<OTAPost>{}
	 
	public partial interface IOTAUsersService : IBaseService<OTAUsers>{}
	 
	public partial interface ISchoolListService : IBaseService<SchoolList>{}
	 
	public partial interface ISysNoticeListService : IBaseService<SysNoticeList>{}
	 
	public partial interface ISysNoticeTypeService : IBaseService<SysNoticeType>{}
	 
	public partial interface IUsersService : IBaseService<Users>{}
	}



