
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-20 17:51:09 by KeHen
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Ast.IBll;
using Ast.Models;

namespace Ast.Bll
{	 
	 
	public partial class ArticleChildCommentService:BaseService<ArticleChildComment>,IArticleChildCommentService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ArticleChildCommentDal;
        }
	}
	 
	public partial class ArticleCommentListService:BaseService<ArticleCommentList>,IArticleCommentListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ArticleCommentListDal;
        }
	}
	 
	public partial class ArticleListService:BaseService<ArticleList>,IArticleListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ArticleListDal;
        }
	}
	 
	public partial class ArticleMarkListService:BaseService<ArticleMarkList>,IArticleMarkListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ArticleMarkListDal;
        }
	}
	 
	public partial class ArticleTypeListService:BaseService<ArticleTypeList>,IArticleTypeListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ArticleTypeListDal;
        }
	}
	 
	public partial class BannerListService:BaseService<BannerList>,IBannerListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.BannerListDal;
        }
	}
	 
	public partial class ClubChildCommentService:BaseService<ClubChildComment>,IClubChildCommentService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ClubChildCommentDal;
        }
	}
	 
	public partial class ClubPostCommentListService:BaseService<ClubPostCommentList>,IClubPostCommentListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ClubPostCommentListDal;
        }
	}
	 
	public partial class ClubPostListService:BaseService<ClubPostList>,IClubPostListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ClubPostListDal;
        }
	}
	 
	public partial class ClubPostTypeService:BaseService<ClubPostType>,IClubPostTypeService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.ClubPostTypeDal;
        }
	}
	 
	public partial class Hc_ArticleListService:BaseService<Hc_ArticleList>,IHc_ArticleListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.Hc_ArticleListDal;
        }
	}
	 
	public partial class Hc_BannerListService:BaseService<Hc_BannerList>,IHc_BannerListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.Hc_BannerListDal;
        }
	}
	 
	public partial class Hc_WebMenuService:BaseService<Hc_WebMenu>,IHc_WebMenuService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.Hc_WebMenuDal;
        }
	}
	 
	public partial class Hc_WebSettingService:BaseService<Hc_WebSetting>,IHc_WebSettingService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.Hc_WebSettingDal;
        }
	}
	 
	public partial class LinksListService:BaseService<LinksList>,ILinksListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.LinksListDal;
        }
	}
	 
	public partial class MemberArticleListService:BaseService<MemberArticleList>,IMemberArticleListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.MemberArticleListDal;
        }
	}
	 
	public partial class MemberCommentListService:BaseService<MemberCommentList>,IMemberCommentListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.MemberCommentListDal;
        }
	}
	 
	public partial class MemberCourseListService:BaseService<MemberCourseList>,IMemberCourseListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.MemberCourseListDal;
        }
	}
	 
	public partial class MemberImgListService:BaseService<MemberImgList>,IMemberImgListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.MemberImgListDal;
        }
	}
	 
	public partial class MemberListService:BaseService<MemberList>,IMemberListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.MemberListDal;
        }
	}
	 
	public partial class OTADepartmentService:BaseService<OTADepartment>,IOTADepartmentService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTADepartmentDal;
        }
	}
	 
	public partial class OTAFuncMenusService:BaseService<OTAFuncMenus>,IOTAFuncMenusService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTAFuncMenusDal;
        }
	}
	 
	public partial class OTALoginLogService:BaseService<OTALoginLog>,IOTALoginLogService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTALoginLogDal;
        }
	}
	 
	public partial class OTAMailListService:BaseService<OTAMailList>,IOTAMailListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTAMailListDal;
        }
	}
	 
	public partial class OTAMenuService:BaseService<OTAMenu>,IOTAMenuService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTAMenuDal;
        }
	}
	 
	public partial class OTAMsgListService:BaseService<OTAMsgList>,IOTAMsgListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTAMsgListDal;
        }
	}
	 
	public partial class OTAPostService:BaseService<OTAPost>,IOTAPostService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTAPostDal;
        }
	}
	 
	public partial class OTAUsersService:BaseService<OTAUsers>,IOTAUsersService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.OTAUsersDal;
        }
	}
	 
	public partial class SchoolListService:BaseService<SchoolList>,ISchoolListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.SchoolListDal;
        }
	}
	 
	public partial class SysNoticeListService:BaseService<SysNoticeList>,ISysNoticeListService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.SysNoticeListDal;
        }
	}
	 
	public partial class SysNoticeTypeService:BaseService<SysNoticeType>,ISysNoticeTypeService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.SysNoticeTypeDal;
        }
	}
	 
	public partial class UsersService:BaseService<Users>,IUsersService
	{
	  public override void SetCurrentDal()
        {
            CurrentDal = DbSession.UsersDal;
        }
	}
	}



